import { SharingService } from "./sharing.service";
import { ShareLinkEntity } from "../entities/share-link.entity";
import { FileEntity } from "../entities/file.entity";
import { UserEntity } from "../entities/user.entity";
import { NotFoundException, BadRequestException } from "@nestjs/common";
import { UploadSessionStatusCheck1746825050000 } from "../migrations/1746825050000-UploadSessionStatusCheck";
import { ShareLinksTokenUnique1746825040000 } from "../migrations/1746825040000-ShareLinksTokenUnique";

describe("SharingService - Authorization Boundary", () => {
  let service: SharingService;
  let mockShareLinkRepository: any;
  let mockFileRepository: any;
  let mockUserRepository: any;
  let mockConfigService: any;

  beforeEach(() => {
    mockShareLinkRepository = {
      findOne: jest.fn(),
      find: jest.fn(),
      create: jest.fn(),
      save: jest.fn(),
    };
    mockFileRepository = {
      findOne: jest.fn(),
    };
    mockUserRepository = {
      findOne: jest.fn(),
    };
    mockConfigService = {
      get: jest.fn((key) => {
        if (key === "MAX_SHARE_SIZE") return "104857600";
        if (key === "ALLOWED_SHARE_MIME_TYPES")
          return "image/png,image/jpeg,application/pdf";
        return undefined;
      }),
    };

    service = new SharingService(
      mockShareLinkRepository,
      mockFileRepository,
      mockUserRepository,
      mockConfigService,
    );
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe("createShareLink", () => {
    it("should create share link when file belongs to user", async () => {
      const file = {
        id: 1,
        userId: 1,
        name: "test.png",
        mimeType: "image/png",
        size: 100,
        isFolder: false,
      };
      const user = { id: 1, email: "user@example.com" };
      mockFileRepository.findOne.mockResolvedValue(file);
      mockUserRepository.findOne.mockResolvedValue(user);
      mockShareLinkRepository.create.mockReturnValue({});
      mockShareLinkRepository.save.mockResolvedValue({});

      const result = await service.createShareLink(1, 1, {});
      expect(result).toBeDefined();
      expect(mockFileRepository.findOne).toHaveBeenCalledWith({
        where: { id: 1, userId: 1 },
      });
    });

    it("should throw NotFoundException when file belongs to another user", async () => {
      mockFileRepository.findOne.mockResolvedValue(null);

      await expect(service.createShareLink(1, 2, {})).rejects.toThrow(
        NotFoundException,
      );
      expect(mockFileRepository.findOne).toHaveBeenCalledWith({
        where: { id: 2, userId: 1 },
      });
    });

    it("should throw NotFoundException when file does not exist", async () => {
      mockFileRepository.findOne.mockResolvedValue(null);

      await expect(service.createShareLink(1, 999, {})).rejects.toThrow(
        NotFoundException,
      );
      expect(mockFileRepository.findOne).toHaveBeenCalledWith({
        where: { id: 999, userId: 1 },
      });
    });

    it("should throw BadRequestException when file type is not allowed for sharing", async () => {
      const file = {
        id: 1,
        userId: 1,
        name: "test.exe",
        mimeType: "application/x-msdownload",
        size: 100,
        isFolder: false,
      };
      mockFileRepository.findOne.mockResolvedValue(file);

      await expect(service.createShareLink(1, 1, {})).rejects.toThrow(
        BadRequestException,
      );
    });

    it("should throw BadRequestException when file size exceeds maximum shareable size", async () => {
      const file = {
        id: 1,
        userId: 1,
        name: "large.png",
        mimeType: "image/png",
        size: 200 * 1024 * 1024,
        isFolder: false,
      };
      mockFileRepository.findOne.mockResolvedValue(file);

      await expect(service.createShareLink(1, 1, {})).rejects.toThrow(
        BadRequestException,
      );
    });

    it("should generate unique tokens for different share links (F-04)", async () => {
      const file = {
        id: 1, userId: 1, name: "test.png", mimeType: "image/png", size: 100, isFolder: false,
      };
      const user = { id: 1, email: "user@example.com" };
      mockFileRepository.findOne.mockResolvedValue(file);
      mockUserRepository.findOne.mockResolvedValue(user);
      mockShareLinkRepository.create.mockReturnValue({});
      mockShareLinkRepository.save.mockResolvedValue({});

      const result1 = await service.createShareLink(1, 1, {});
      const result2 = await service.createShareLink(1, 1, {});

      // Token is generated by uuidv4 - extremely high entropy
      // Verify that the save was called with a token (non-empty string)
      expect(mockShareLinkRepository.create).toHaveBeenCalledTimes(2);
      const createCalls = mockShareLinkRepository.create.mock.calls;
      expect(createCalls[0][0].token).toBeDefined();
      expect(createCalls[0][0].token).toHaveLength(36); // uuid v4 format
      expect(createCalls[1][0].token).toBeDefined();
      expect(createCalls[1][0].token).toHaveLength(36);
      expect(createCalls[0][0].token).not.toBe(createCalls[1][0].token);
    });

    it("should look up share link by token with isActive filter (F-04)", async () => {
      mockShareLinkRepository.findOne.mockResolvedValue({ token: "test-token", isActive: true });

      await service.findShareByToken("test-token");

      expect(mockShareLinkRepository.findOne).toHaveBeenCalledWith({
        where: { token: "test-token", isActive: true },
        relations: ["file", "user"],
      });
    });
  });

  describe("Migration F-04 + F-16", () => {
    it("ShareLinksTokenUnique migration should exist and be reversible", () => {
      expect(ShareLinksTokenUnique1746825040000).toBeDefined();
      const m = new ShareLinksTokenUnique1746825040000();
      expect(m.name).toBe("ShareLinksTokenUnique1746825040000");
      expect(typeof m.up).toBe("function");
      expect(typeof m.down).toBe("function");
    });
  });
});
